force_torque:
  left_ankle_ft:
    sensor_joint: leg_left_6_joint
    frame: leg_left_6_link
  right_ankle_ft:
    sensor_joint: leg_right_6_joint
    frame: leg_right_6_link
imu:
  base_imu:
    frame: imu_link
    gazebo_sensor_name: imu_sensor


